//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.13

pub use super::chats::Entity as Chats;
pub use super::messages::Entity as Messages;
pub use super::users::Entity as Users;
pub use super::workspace::Entity as Workspace;
