//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.13

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "chat_type")]
pub enum ChatType {
    #[sea_orm(string_value = "single")]
    Single,
    #[sea_orm(string_value = "private_channel")]
    PrivateChannel,
    #[sea_orm(string_value = "publish_channel")]
    PublishChannel,
}
